version: '2.2'
services:
  rabbit:
    image: "rabbitmq"
    ports:
     - "5680:5672"
  app:
    build:
      context: app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "5000:5000"
    depends_on:
     - rabbit
  email-confirm-sender:
    build:
      context: email-confirm-sender
      dockerfile: Dockerfile
    restart: always
    depends_on:
     - rabbit
